siteConfig:
  title: Guillermo Rodríguez
  # subTitle: Foo
  # description: About this website..
  # author: My Name
  # email: my@email.com


themeConfig:
  title: Guillermo Rodríguez
  # subTitle: The subtitle shown on the index page.
  nav:
    - text: Home
      link: /
    - text: Vitae
      link: /vitae.html

markdown:
  highlighter: prism
plugins:

  # - resolve: saber-plugin-feed
  - resolve: saber-plugin-query-posts

theme: tufte
