name: Deploy
env:
  GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
on:
  push:
    branches: [ master ]
jobs:
  publish:
    name: Publish website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: guille/guille.github.io
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          path: target
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Deploy
        run: yarn ci-deploy
